kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ppluto-homepage
spec:
  project: default
  source:
    repoURL: https://github.com/ppluto-dev/pluto-homepage-argocd.git
    # TODO: Update path automatically.
    path: auto_branch_pushes/sungbin/add-signup-to-stibee/overlays/prod
    targetRevision: HEAD
  destination:
    # TODO: This has to be `argocd` for ArgoCD's app of apps to work, which is
    #       not ideal.
    #       https://github.com/argoproj/argo-cd/issues/3181#issuecomment-626901858
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
