apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: registry.gitlab.com/ppluto-dev/ppluto-homepage/prod-client
  newTag: 99b04ebcb4557c5034cd7bed8fd869da6270d9b5
