# Cert manager install instruction: https://cert-manager.io/docs/installation/helm/

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cert-manager
spec:
  project: default
  source:
    path: ""
    repoURL: "https://charts.jetstack.io/"
    targetRevision: v1.10.0
    chart: cert-manager
    helm:
      values: ""
      parameters:
        - name: extraArgs
          value: "{--feature-gates=ExperimentalGatewayAPISupport=true}"
        - name: installCRDs
          value: "true"
  destination:
    name: ""
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
