kind: Deployment
apiVersion: apps/v1
metadata:
  name: ppluto-homepage
spec:
  selector:
    matchLabels:
      app: ppluto-homepage
  replicas: 2
  template:
    metadata:
      labels:
        app: ppluto-homepage
    spec:
      containers:
        - name: ppluto-homepage
          image: registry.gitlab.com/ppluto-dev/ppluto-main/homepage:UNSPECIFIED
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: gitlab-container-registry
