# Istio install instruction https://istio.io/latest/docs/setup/install/helm/

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: istio
spec:
  project: default
  source:
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    path: ""
    # MANUAL_UPDATE: https://artifacthub.io/packages/search?org=istio
    targetRevision: 1.13.9
    chart: base
    helm:
      values: ""
      parameters:
        - name: defaultRevision
          value: default
  destination:
    name: ""
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
