apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: registry.gitlab.com/ppluto-dev/ppluto-main/homepage
  newTag: f200dec63fcf472dee5d7fdcc99c6e1afdd92008db8869edd9c8a896d84a339e

