apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: registry.gitlab.com/ppluto-dev/ppluto-main/homepage
  newTag: 2fef93c0291d0bfcff5c75d82ab2cf4187855fbcf3f53686422efce5354ddd91

